-- Run this in Supabase SQL Editor.
create table if not exists public.eoi_profiles (
  id bigint generated by default as identity primary key,
  noc_code text not null check (noc_code ~ '^[0-9]{5}$'),
  region text not null check (region in (
    'Greater Toronto Area',
    'Central Ontario',
    'Eastern Ontario',
    'Southwestern Ontario',
    'Northern Ontario'
  )),
  eoi_score integer not null check (eoi_score between 0 and 200),
  created_at timestamptz not null default now()
);

alter table public.eoi_profiles enable row level security;

-- Anyone can read community-submitted NOC/region/score rows.
create policy "public read eoi profiles"
on public.eoi_profiles for select
to anon
using (true);

-- Anonymous users can submit only rows that pass table constraints.
create policy "public insert eoi profiles"
on public.eoi_profiles for insert
to anon
with check (true);

-- No anonymous update or delete policies are created.

create index if not exists eoi_profiles_noc_region_idx
on public.eoi_profiles (noc_code, region);
